--UC1:
CREATE DATABASE ADDRESSBOOK_SERVICE
SELECT * FROM SYS.DATABASES
USE ADDRESSBOOK_SERVICE

--UC2:
CREATE TABLE ADDRESS_BOOK(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
CITY VARCHAR(25) NOT NULL,
STATE VARCHAR(25) NOT NULL,
ZIP_CODE FLOAT NOT NULL,
PHONE_NUMBER FLOAT NOT NULL,
EMAIL VARCHAR(50) NOT NULL)

SELECT * FROM ADDRESS_BOOK
